spring:
  application:
    name: pacs-server
  datasource:
    url: jdbc:h2:file:./.data/pacs;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
  threads:
    virtual:
      enabled: true
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: health,info
dicom:
  pacs:
    local-aet: MY_PACS
    local-port: 11112
    storage-dir: .data\storage
    file-path-pattern: "{00100020}\\{0020000D}\\{0020000E}\\{00080018}.dcm"
    idle-timeout: 1200000
    db-type: h2
    netty:
      boss-threads: 1
      worker-threads: 0
      max-connections: 1000
      send-buffer-size: 1MB
      receive-buffer-size: 1MB
    scu:
      enabled: true
      find-retry-count: 10
      connect-timeout: 10000
    scp:
      enabled: true
      find-enabled: true
      move-enabled: true
      store-enabled: true
    security:
      tls-enabled: false
      keystore-path:
      truststore-path:
      aet-whitelist: []
    dicomweb:
      auth-enabled: true
      jwt-secret: change-me
    sync:
      enabled: false
      dispatcher-interval-ms: 60000
      initial-delay-ms: 30000
      lock-at-most-ms: 120000
      pull-jobs: []
      push-jobs: []
