CREATE TABLE pacs_patient (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id VARCHAR(128) NOT NULL,
    issuer_of_patient_id VARCHAR(128) NOT NULL DEFAULT '',
    patient_name VARCHAR(256),
    patient_sex VARCHAR(4),
    patient_birth_date VARCHAR(32),
    extra_tags CLOB,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_patient_id UNIQUE (patient_id, issuer_of_patient_id)
);
