CREATE TABLE pacs_study (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_fk BIGINT NOT NULL,
    study_instance_uid VARCHAR(128) NOT NULL,
    accession_no VARCHAR(128),
    study_date VARCHAR(16),
    study_time VARCHAR(16),
    study_desc VARCHAR(256),
    modalities_in_study VARCHAR(128),
    referring_dr VARCHAR(128),
    num_series INT NOT NULL DEFAULT 0,
    num_instances INT NOT NULL DEFAULT 0,
    extra_tags CLOB,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_study_uid UNIQUE (study_instance_uid),
    CONSTRAINT fk_study_patient FOREIGN KEY (patient_fk) REFERENCES pacs_patient(id)
);

CREATE INDEX idx_study_patient_fk ON pacs_study(patient_fk);
CREATE INDEX idx_study_accession_no ON pacs_study(accession_no);
CREATE INDEX idx_study_date ON pacs_study(study_date);
