CREATE TABLE pacs_series (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    study_fk BIGINT NOT NULL,
    series_instance_uid VARCHAR(128) NOT NULL,
    modality VARCHAR(32),
    series_desc VARCHAR(256),
    body_part_examined VARCHAR(64),
    series_number INT,
    num_instances INT NOT NULL DEFAULT 0,
    extra_tags TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_series_uid UNIQUE (series_instance_uid),
    CONSTRAINT fk_series_study FOREIGN KEY (study_fk) REFERENCES pacs_study(id)
);

CREATE INDEX idx_series_study_fk ON pacs_series(study_fk);
CREATE INDEX idx_series_modality ON pacs_series(modality);
