CREATE TABLE pacs_instance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    series_fk BIGINT NOT NULL,
    sop_instance_uid VARCHAR(128) NOT NULL,
    sop_class_uid VARCHAR(64),
    transfer_syntax_uid VARCHAR(64),
    instance_number INT,
    file_path VARCHAR(512) NOT NULL,
    file_size BIGINT,
    file_md5 VARCHAR(32),
    extra_tags TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_sop_instance_uid UNIQUE (sop_instance_uid),
    CONSTRAINT fk_instance_series FOREIGN KEY (series_fk) REFERENCES pacs_series(id)
);

CREATE INDEX idx_instance_series_fk ON pacs_instance(series_fk);
