CREATE TABLE sync_execution (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_name VARCHAR(128) NOT NULL,
    job_type VARCHAR(16) NOT NULL,
    target_aet VARCHAR(64) NOT NULL,
    status VARCHAR(16) NOT NULL,
    examined_count INT NOT NULL DEFAULT 0,
    transferred_study_count INT NOT NULL DEFAULT 0,
    transferred_instance_count INT NOT NULL DEFAULT 0,
    skipped_existing_count INT NOT NULL DEFAULT 0,
    duplicate_skip_count INT NOT NULL DEFAULT 0,
    source_loop_skip_count INT NOT NULL DEFAULT 0,
    criteria_json CLOB,
    error_message VARCHAR(1024),
    started_at TIMESTAMP NOT NULL,
    finished_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_sync_execution_started_at ON sync_execution(started_at);
CREATE INDEX idx_sync_execution_job_name ON sync_execution(job_name);
