CREATE TABLE sync_job_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_name VARCHAR(128) NOT NULL,
    job_type VARCHAR(16) NOT NULL,
    target_aet VARCHAR(64) NOT NULL,
    destination_aet VARCHAR(64),
    patient_id VARCHAR(64),
    modality VARCHAR(16),
    study_date_lookback_days INT NOT NULL DEFAULT 1,
    prevent_loop_to_source BOOLEAN NOT NULL DEFAULT TRUE,
    skip_remote_duplicates BOOLEAN NOT NULL DEFAULT TRUE,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_sync_job_name UNIQUE (job_name)
);

CREATE INDEX idx_sync_job_enabled ON sync_job_config(enabled);
CREATE INDEX idx_sync_job_type ON sync_job_config(job_type);
